name: Build

on:
#  schedule: # execute every 24 hours
#    - cron: "* */24 * * *"
  pull_request:
    types: [ closed ]

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'
          architecture: 'x64'

      - name: Python Poetry Action
        uses: abatilo/actions-poetry@v2.1.3

      - name: Setup Poetry
        run:  poetry install

      - name: build
        run: |
          poetry run python -m nuitka --assume-yes-for-downloads --standalone run.py
          mv run.build ffu-core_0.1.0
          zip -r ffu-core_0.1.0.zip ffu-core_0.1.0

      - name: GH Release
        uses: softprops/action-gh-release@v0.1.14
        with:
          generate_release_notes: true
          files: ffu-core_0.1.0.zip
