name: Build

on:
  # schedule: # execute every 24 hours
  #   - cron: "* */24 * * *"
  # pull_request:
  #   types: [ closed ]
  push:
    tags:
      - "v[0-9]+\\.[0-9]+\\.[0-9]+"

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Set version
        id: version
        run: |
          REPOSITORY=$(echo ${{ github.repository }} | sed -e "s#.*/##")
          VERSION=$(echo ${{ github.ref }} | sed -e "s#refs/tags/##g")
          echo ::set-output name=version::$VERSION
          echo ::set-output name=filename::$REPOSITORY-$VERSION
          echo "Version $VERSION"

      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'
          architecture: 'x64'

      - name: Python Poetry Action
        uses: abatilo/actions-poetry@v2.1.3

      - name: Setup Poetry
        run:  poetry install

      - name: build
        run: |
          poetry run python -m nuitka --assume-yes-for-downloads --standalone run.py
          zip -r ${{ steps.version.outputs.filename }}.zip run.dist

      - name: GH Release
        uses: softprops/action-gh-release@v0.1.14
        with:
          generate_release_notes: true
          files: ${{ steps.version.outputs.filename }}.zip
